name: ItemFrameClipping
version: '${project.version}'
main: green.misc.ItemFrameClipping
api-version: 1.18
authors: [ GreenZ114 ]
description: Right click on item frames with sheers to make them invisible
